FROM postgres:13

# Variables d'environnement pour la configuration de Postgres
ENV POSTGRES_DB=tsundoku_postgres
ENV POSTGRES_HOST=localhost
ENV POSTGRES_USER=54j48gyFJt7BFv-user
ENV POSTGRES_PASSWORD=t7Fy5B84vJFg4j
ENV POSTGRES_PORT=5432

# port Postgres
EXPOSE 5432

# Commande pour démarrer Postgres
CMD ["postgres"]